const cmdList = [
  "npm run Hey👋",
  "Nice To Meet You 🤝",
  "My Name Is Shreyansh.",
  "Let Me Give You Quik Introduction About Me.",
  "I'm currently studying📚 computer engineer bachelor degree in ganpat university",
  "I'm Full Stack Web Developer",
  "Who Build Projects For Fun😋",
  "Who Build Projects For Knowledge",
  "I know React.js,Next.js",
  "I know Typescript, Javascript, Node",
  "I know Html5,Css3",
  "My Programming journey begins when I'm in 11th standard.",
  "In our curriculum, there is one chapter called java.",
  "I got into that chapter for the whole semester.",
  "And then I start learning web development thanks to youtube.",
  "After That, So many Things Happen.",
  "And now i'm talking to you😅",
  "Btw I love making friends🤩",
  "So hit me up with an email just to say hi!!👋",
  "Or we can Talk About video games too 🎮",
  "Byyyyyy💓",
  "Peace✌",
];

export default cmdList;
